DROP TABLE T_JDBC_BASIC_STUDENT;
CREATE table T_JDBC_BASIC_STUDENT(
	`stuid` bigint(20) unsigned NOT NULL,
	`stuname` varchar(20) default NULL,
	PRIMARY KEY (`stuid`),
	UNIQUE KEY (`stuname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO T_JDBC_BASIC_STUDENT VALUES ('1', 'Sondy');
INSERT INTO T_JDBC_BASIC_STUDENT VALUES ('2', 'Lanny');
INSERT INTO T_JDBC_BASIC_STUDENT VALUES ('3', 'Michael Woo');